FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    openjdk-21-jre \
    python3 \
    && rm -rf /var/lib/apt/lists/*           

WORKDIR /app

CMD [ "python3", "run", "myapp" ] 